### ISSUE TITLE
Make global ban list case-insensitive

### ISSUE THREAD

**Issue by mags0ft** [AXOMEstudios/austeritas#11]
**Describe the bug**
Austeritas is not able to catch cheaters when written in the wrong case.

**To Reproduce**
1. Write "player123" into the banned.json list
2. Start Austeritas
3. Anywhere, enter "Player123"
4. Austeritas will not catch the cheater.

**Expected behavior**
Austeritas should ignore upper- or lowercase letters in the query.

**Comment by AXOMEstudios** [comment]
Added
