### ISSUE TITLE
Re-structure app to have a „src“ folder

### ISSUE THREAD

**Issue by AXOMEstudios** [AXOMEstudios/austeritas#15]
**Is your feature request related to a problem? Please describe.**
The maintenance of a codebase not using a `src` directory can get very challenging over time as non-code files are getting mixed up with code.

**Describe the solution you'd like**
By moving all necessary files used by the code into a folder called `src`, `app`, `austeritas` or similar, more conciseness can be achieved.

**Describe alternatives you've considered**
An alternative would be to move non-code files in their own directory, but this is very uncommon and does not work as well.

**Comment by mags0ft** [comment]
Finished!
